INSERT INTO TB_USUARIO
(ID, ID_T_LV_TIPOUSUARIO, ID_T_LV_ESTADOUSUARIO, ID_T_LV_TIPOIDENTIFICACION, NUMIDENTIFICACION, PRIMERNOMBRE, SEGUNDONOMBRE, PRIMERAPELLIDO, SEGUNDOAPELLIDO, FECHANACIMIENTO, GENERO, TELEFONOFIJO, TELEFONOCELULAR, USUARIO, CONTRASENA, ID_T_LV_PROGRAMAACADEMICO, ID_T_LV_DEPENDENCIA, CREADOPOR, CREADOEN, MODIFICADOPOR, MODIFICADOEN)
VALUES (1, 27, 30, 1, '999999999', 'admin', null, 'UNIAJC', null,TO_DATE('01/01/2007 00:00:00', 'DD/MM/YYYY HH24:MI:SS'),'M','6652828', null,'ideabank.uniajc@gmail.com','/GkLBiwdgMRjskSjo2u4mQ==',39,44,'admin.UNIAJC',TO_DATE('25/05/2017 23:28:55', 'DD/MM/YYYY HH24:MI:SS'),Null,Null)
/
